export const DASHBOARD_DEFAULTS = {
  PREDICTED_SCORE: 498,
  TARGET_SCORE: 540,
  MAX_SCORE: 700,
  STREAK_DAYS: 0,
  NATIONAL_RANK: 0,
  DEFAULT_UNIVERSITY: "Addis Ababa University (AAU)",
  DAYS_UNTIL_EXAM: 118,
  CANDIDATE_NAME: "Candidate",
  TREND_FALLBACK: [45, 52, 58, 64, 70, 72, 78],
} as const;
